apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: k8s-at-home
  pass_credentials_all: false
  password: ""
  url: https://k8s-at-home.com/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nextcloud
  pass_credentials_all: false
  password: ""
  url: https://nextcloud.github.io/helm/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: longhorn
  pass_credentials_all: false
  password: ""
  url: https://charts.longhorn.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: rook-release
  pass_credentials_all: false
  password: ""
  url: https://charts.rook.io/release
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: plex
  pass_credentials_all: false
  password: ""
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://traefik.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kubitodev
  pass_credentials_all: false
  password: ""
  url: https://charts.kubito.dev
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cnpg
  pass_credentials_all: false
  password: ""
  url: https://cloudnative-pg.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kedacore
  pass_credentials_all: false
  password: ""
  url: https://kedacore.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cnpg-grafana
  pass_credentials_all: false
  password: ""
  url: https://cloudnative-pg.github.io/grafana-dashboards
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: argo-cd
  pass_credentials_all: false
  password: ""
  url: https://argoproj.github.io/argo-helm
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: passbolt
  pass_credentials_all: false
  password: ""
  url: https://download.passbolt.com/charts/passbolt
  username: ""
