prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Datatrail
    filters: is:open repo:chimefrb/datatrail repo:chimefrb/datatrail-admin repo:chimefrb/datatrail-cli
issuesSections:
  - title: My Issues
    filters: is:open author:@me
    layout:
      author:
        hidden: true
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Datatrail
    filters: is:open repo:chimefrb/datatrail repo:chimefrb/datatrail-admin repo:chimefrb/datatrail-cli
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues:
    - key: v
      command: >
        tmux split-window -h -c {{.RepoPath}} '
          nvim -c ":Octo issue edit {{.IssueNumber}}"
        '
    - key: d
      name: Develop
      command: >
        tmux split-window -h -c {{.RepoPath}} '
          gh issue develop -c {{.IssueNumber}}
          nvim
        '
    - key: p
      name: Create PR
      command: >
        tmux split-window -h -c {{.RepoPath}} '
          nvim -c ":Octo pr create {{.IssueNumber}}"
        '
  prs:
    - key: C
      command: >
        tmux split-window -h -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":Octo pr edit {{.PrNumber}}"
        '
    - key: V
      command: >
        tmux split-window -h -c {{.RepoPath}} '
          nvim -c ":Octo pr edit {{.PrNumber}}"
        '
repoPaths:
  CHIMEFRB/*: ~/Workspace/CHIME/*
  chime-experiment/*: ~/Workspace/ExperimentCHIME/*
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: delta
confirmQuit: false
